CREATE TABLE "HOBBY" (
	"HOBBY_CODE"	VARCHAR(20)		NOT NULL,
	"HOBBY_NAME"	NVARCHAR2(20)		NOT NULL,
	"HOBBY_INFO"	VARCHAR2(4000)		NOT NULL,
	"HOBBY_ICON"	NVARCHAR2(200)		NULL,
	"PARENT_CODE"	VARCHAR(20)		NULL,
	"HOBBY_LEVEL"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "HOBBY"."HOBBY_CODE" IS '취미 코드 (PK)';

COMMENT ON COLUMN "HOBBY"."HOBBY_NAME" IS '취미명';

COMMENT ON COLUMN "HOBBY"."HOBBY_INFO" IS '취미 상세 정보';

COMMENT ON COLUMN "HOBBY"."HOBBY_ICON" IS '취미 아이콘';

COMMENT ON COLUMN "HOBBY"."PARENT_CODE" IS '취미 부모 코드';

COMMENT ON COLUMN "HOBBY"."HOBBY_LEVEL" IS '취미 레벨';

COMMENT ON COLUMN "HOBBY"."BOARD_CODE" IS '게시판 코드 번호 (PK)';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(30)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"AUTHOR_LEVEL"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

SELECT * FROM "MEMBER"; 

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."AUTHOR_LEVEL" IS '회원 권한 등급';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부';

CREATE TABLE "PENALTY" (
	"PENALTY_NO"	NUMBER		NOT NULL,
	"PENALTY_TYPE"	VARCHAR2(20)		NOT NULL,
	"PENALTY_START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PENALTY_END_DATE"	DATE		NULL,
	"PENALTY_REASON"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PENALTY"."PENALTY_NO" IS '제재 번호 (PK)';

COMMENT ON COLUMN "PENALTY"."PENALTY_TYPE" IS '제재 유형';

COMMENT ON COLUMN "PENALTY"."PENALTY_START_DATE" IS '제재 시작일';

COMMENT ON COLUMN "PENALTY"."PENALTY_END_DATE" IS '제재 종료일';

COMMENT ON COLUMN "PENALTY"."PENALTY_REASON" IS '제재 사유';

COMMENT ON COLUMN "PENALTY"."MEMBER_NO" IS '회원 번호(PK)';

CREATE TABLE "MEMBER_HOBBY" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"HOBBY_CODE"	VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_HOBBY"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER_HOBBY"."HOBBY_CODE" IS '취미 코드 (PK)';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"COMMENT_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호 (PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호 (PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_NO2" IS '부모 댓글 번호 (FK)';

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"AUTH_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"AUTH_KEY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_CODE" IS '인증키 구분 번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증키';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_DATE" IS '인증키 생성일';

CREATE TABLE "COMMENT_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "COMMENT_LIKE"."COMMENT_NO" IS '댓글 번호 (PK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"BOARD_VIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호 (PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_VIEW_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드 번호 (PK)';

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호 (PK)';

CREATE TABLE "PROFILE_IMG" (
	"PROFILE_NO"	NUMBER		NOT NULL,
	"PROFILE_PATH"	VARCHAR2(500)		NOT NULL,
	"PROFILE_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"PROFILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"PROFILE_UPDATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_NO" IS '프로필 이미지 번호 (PK)';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_PATH" IS '프로필 이미지 경로';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_ORIGINAL_NAME" IS '프로필 이미지 원본명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_RENAME" IS '프로필 이미지 변경명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_UPDATE_DATE" IS '프로필 이미지 업로드일';

COMMENT ON COLUMN "PROFILE_IMG"."MEMBER_NO" IS '회원 번호(PK)';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 코드 번호 (PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 명';

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER		NOT NULL,
	"BOARD_IMG_PATH"	VARCHAR2(500)		NOT NULL,
	"BOARD_IMG_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"BOARD_IMG_RENAME"	VARCHAR2(100)		NOT NULL,
	"BOARD_IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NO" IS '게시글 이미지 번호 (PK)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_PATH" IS '게시글 이미지 경로';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORIGINAL_NAME" IS '게시글 이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_RENAME" IS '게시글 이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORDER" IS '게시글 이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호 (PK)';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_REASON"	NVARCHAR2(100)		NOT NULL,
	"REPORT_DETAIL"	VARCHAR2(4000)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_STATUS"	VARCHAR2(20)	DEFAULT 'PENDING'	NOT NULL,
	"REPORTER_MEMBER_NO"	NUMBER		NOT NULL,
	"REPORTED_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 번호(PK)';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고 사유';

COMMENT ON COLUMN "REPORT"."REPORT_DETAIL" IS '신고 상세 내용';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고 날짜';

COMMENT ON COLUMN "REPORT"."REPORT_STATUS" IS '신고 상황';

COMMENT ON COLUMN "REPORT"."REPORTER_MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "REPORT"."REPORTED_MEMBER_NO" IS '회원 번호(PK)';

ALTER TABLE "HOBBY" ADD CONSTRAINT "PK_HOBBY" PRIMARY KEY (
	"HOBBY_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PENALTY" ADD CONSTRAINT "PK_PENALTY" PRIMARY KEY (
	"PENALTY_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "PK_MEMBER_HOBBY" PRIMARY KEY (
	"MEMBER_NO",
	"HOBBY_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_CODE"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"COMMENT_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "PK_PROFILE_IMG" PRIMARY KEY (
	"PROFILE_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "HOBBY" ADD CONSTRAINT "FK_HOBBY_TO_HOBBY_1" FOREIGN KEY (
	"PARENT_CODE"
)
REFERENCES "HOBBY" (
	"HOBBY_CODE"
);

ALTER TABLE "HOBBY" ADD CONSTRAINT "FK_BOARD_TYPE_TO_HOBBY_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "PENALTY" ADD CONSTRAINT "FK_MEMBER_TO_PENALTY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_HOBBY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_HOBBY" ADD CONSTRAINT "FK_HOBBY_TO_MEMBER_HOBBY_1" FOREIGN KEY (
	"HOBBY_CODE"
)
REFERENCES "HOBBY" (
	"HOBBY_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"COMMENT_NO2"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "FK_MEMBER_TO_AUTH_KEY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "FK_MEMBER_TO_PROFILE_IMG_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"REPORTER_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_2" FOREIGN KEY (
	"REPORTED_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

